CC = gcc
RM = rm -f

0:
	@echo 'Input num to complie'

# 进程简单操作
# This file to get some user info from env
1:
	$(CC) p1.c -o p1


# This file to create a child process
2: 
	$(CC) p2.c -o p2

# 检查邮箱程序
3: 
	$(CC) p3.c -o p3

# 文件操作:
# 复制文件
4:
	$(CC) p4.c -o p4

clean:
	$(RM) p1 p2 p3 p4
	
