CC = g++
RM = rm -f

0:
	@echo 'Input num to complie'

# Json 库的简单添加与打印
1:
	$(CC) p1.cc -o p1

# Json 库的arry初始化方式
2:
	$(CC) p2.cc -o p2

# Json 库中通过key获取value, 测试类型错误和key错误的异常
3:
	$(CC) p3.cc -o p3

# Json 库array的赋值与捕获类型错误和越界错误异常
4:
	$(CC) p4.cc -o p4

clean:
	$(RM) p1 p2 p3 p4
	
