CXX = g++
CC  = gcc
RM = rm -f

0:
	@echo 'Input num to complie'

# 查看当前系统是字节序
1:
	$(CC) p1.c -o p1

# 测试listen函数
2:
	$(CXX) p2.cpp -o p2
# accept函数,获取到对方的ip和port的简单实例
3:
	$(CXX) p3.cpp -o p3

clean:
	$(RM) p1 p2 p3
