#! /bin/bash
case "$1" in
	1)
	month=January;;
	2)
	month=February;;
	3)
	month=March;;
	4)
	month=April;;
	5)
	month=May;;
	6)
	month=June;;
	7)
	month=July;;
	8)
	month=Aguest;;
	9)
	month=September;;
	10)
	month=October;;
	11)
	month=November;;
	12)
	month=December;;
	*)
	month=error;;
esac

echo "Month is $month"

