CC = gcc
RM = rm -f

0:
	@echo 'Input num to complie'

# 获取线程id
# This file to get some user info from env
1:
	$(CC) p1.c -lpthread -o p1

# 创建线程
2:
	$(CC) p2.c -lpthread -o p2

# 实现创建线程传入多个参数
3:
	$(CC) p3.c -lpthread -o p3

# 作业: 
4:
	$(CC) p4.c -lpthread -o p4

# 验证线程的退出方式: 
5:
	$(CC) p5.c -lpthread -o p5

# 验证线程的退出方式: 
6:
	$(CC) p6.c -lpthread -o p6

# 信号量
7:
	$(CC) p7.c -lpthread -o p7

# 信号量, 严格实现同步
8:
	$(CC) p8.c -lpthread -o p8

clean:
	$(RM) p1 p2 p3 p4 p5 p6 p7 p8
	
