CC = gcc
RM = rm -f

0:
	@echo 'Input num to complie'

# 获取线程id
# This file to get some user info from env
1:
	$(CC) p1.c -lpthread -o p1

# 创建线程
2:
	$(CC) p2.c -lpthread -o p2

# 实现创建线程传入多个参数
3:
	$(CC) p3.c -lpthread -o p3

# 作业: 
4:
	$(CC) p4.c -lpthread -o p4

clean:
	$(RM) p1 p2 p3 p4
	
